server:
  port: 8888
spring:
  profiles:
     active: dev
  application:
    name: corn-gateway   
     
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
      
logging:
  level:
    org.springframework.cloud.gateway: debug