server:
   port: 9001

corn: 
   interceptor: 
       exclude-path: 
         - /js/**
         - /css/**
         - /img/**
         - /images/**
         - /fonts/**
         - /favicon.ico
         - /oauth/**
         - /alive
         - /oauth/**

security:
   oauth2:
      resource:
         id: order
         # 资源服务器相关过滤器链的顺序
         filter-order: 3

spring:
#  autoconfigure:
#     exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
#  main:
#     allow-bean-definition-overriding: true
  application:
    name: corn-auth-test
  redis: 
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 
      # 毫秒
      timeout: 200 
      lettuce:
         pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            max-wait: -1
   
eureka:
   client:
      # 单独运行设置为 false，集群运行设置为 true
      register-with-eureka: false
      fetch-registry: false
      service-url:
         defaultZone: http://localhost:8000/eureka/
            
