server:
   port: 8000
   
spring:
   application:
      name: corn-eureka

eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
         defaultZone: http://weicong.xyz:${server.port}/eureka/